#!/usr/bin/env bash
# Cross-tool benchmark for `tsr`. Compares tsr · npm · bun · just · go-task · make
# across four scenarios, driven by hyperfine (statistical, with warmup):
#
#   startup   one task that spawns `true`           per-invocation overhead
#   shell     one task, `echo $HOME && echo done`   shell one-liner ($VAR + &&)
#   localbin  one task calling node_modules/.bin     local-binary resolution (JS only)
#   steps5    one task, 5 sequential commands       in-task sequencing (one launch)
#   graph5    a task with 5 trivial dependencies    dependency-graph overhead
#   graph10   a task with 10 trivial dependencies   graph overhead, scaled
#
# tsr/just/go-task/make express the graph natively (one launch resolves the whole
# graph). npm and bun have no dependency graph, so — as their users actually do —
# the graph scenarios chain N invocations with `&&`; that is exactly why the
# per-invocation cost compounds for them. The point of the benchmark is that
# contrast, not to handicap anyone.
#
# Task definitions live in workspace/ and are generated by gen-workspace.sh.
#
# Usage:  benches/run.sh            # benchmarks every tool that is installed
#         TSR=/path/to/tsr benches/run.sh
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/.." && pwd)"
out="$here/results"
cd "$here/workspace"
mkdir -p "$out"

TSR="${TSR:-$repo/target/release/tsr}"
if [[ ! -x "$TSR" ]]; then
  echo "building tsr (release)…" >&2
  (cd "$repo" && cargo build --release --quiet)
fi
command -v hyperfine >/dev/null 2>&1 || {
  echo "error: hyperfine is required (cargo install hyperfine)" >&2
  exit 1
}

has() { command -v "$1" >/dev/null 2>&1; }

# Build the `npm run … && npm run …` (or bun) chain for a graph of N tasks.
chain() {
  local runner="$1" n="$2" out="" i
  for ((i = 1; i <= n; i++)); do
    [[ -n "$out" ]] && out+=" && "
    out+="$runner s$i"
  done
  printf '%s' "$out"
}

# Run one scenario.
#   $1=name  $2=shell-mode(none|sh)  $3=task/target  $4=graph_n(0)  $5=tools(all|js)
# `js` restricts to the runners that resolve node_modules/.bin (tsr/npm/bun) — the
# only fair set for the local-binary scenario. The list is assembled from what's
# installed.
bench() {
  local name="$1" shellmode="$2" target="$3" graph_n="${4:-0}" tools="${5:-all}"
  local args=(-n tsr "$TSR $target")
  if [[ "$graph_n" -gt 0 ]]; then
    has npm && args+=(-n npm "$(chain 'npm run --silent' "$graph_n")")
    has bun && args+=(-n bun "$(chain 'bun run' "$graph_n")")
  else
    has npm && args+=(-n npm "npm run --silent $target")
    has bun && args+=(-n bun "bun run $target")
  fi
  if [[ "$tools" != "js" ]]; then
    has just && args+=(-n just "just $target")
    has task && args+=(-n task "task $target")
    has make && args+=(-n make "make $target")
  fi

  local shellflag=(--shell=none)
  [[ "$shellmode" == "sh" ]] && shellflag=() # default shell for `&&` chains

  echo "== $name ==" >&2
  hyperfine "${shellflag[@]}" \
    --warmup 20 --min-runs 80 \
    --export-json "$out/$name.json" \
    --export-markdown "$out/$name.md" \
    "${args[@]}"
}

bench startup none noop
bench shell none shell
bench localbin none cli 0 js
bench steps5 none steps5
bench graph5 sh graph5 5
bench graph10 sh graph10 10

echo "results in benches/results/{startup,shell,localbin,steps5,graph5,graph10}.{md,json}" >&2
