#!/usr/bin/env bash
# Cross-tool benchmark for `tsr`. Compares tsr · npm · bun · nub · just · go-task · make
# · mise across the scenarios below, driven by hyperfine (statistical, with warmup):
#
#   startup   one task that spawns `true`           per-invocation overhead
#   shell     one task, `echo $HOME && echo done`   shell one-liner ($VAR + &&)
#   builtins  one task, mkdir+touch+cp+mv+rm        in-process coreutils (SPEC §8.5)
#   globbing  one task, `echo src/*.rs`             in-process glob expansion (§8.1)
#   localbin  one task calling node_modules/.bin     local-binary resolution (JS only)
#   steps5    one task, 5 sequential commands       in-task sequencing (one launch)
#   graph5    a task with 5 trivial dependencies    dependency-graph overhead
#   graph10   a task with 10 trivial dependencies   graph overhead, scaled
#
# tsr/just/go-task/make express the graph natively (one launch resolves the whole
# graph). npm and bun have no dependency graph, so — as their users actually do —
# the graph scenarios chain N invocations with `&&`; that is exactly why the
# per-invocation cost compounds for them. The point of the benchmark is that
# contrast, not to handicap anyone.
#
# Task definitions live in workspace/ and are generated by gen-workspace.sh.
#
# Usage:  benches/run.sh            # benchmarks every tool that is installed
#         TSR=/path/to/tsr benches/run.sh
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/.." && pwd)"
out="$here/results"
cd "$here/workspace"
mkdir -p "$out"

TSR="${TSR:-$repo/target/release/tsr}"
if [[ ! -x "$TSR" ]]; then
  echo "building tsr (release)…" >&2
  (cd "$repo" && cargo build --release --quiet)
fi
command -v hyperfine >/dev/null 2>&1 || {
  echo "error: hyperfine is required (cargo install hyperfine)" >&2
  exit 1
}

has() { command -v "$1" >/dev/null 2>&1; }

# mise refuses to run tasks from an untrusted config; trust the bench workspace.
has mise && mise trust >/dev/null 2>&1 || true

# Build the `npm run … && npm run …` (or bun) chain for a graph of N tasks.
chain() {
  local runner="$1" n="$2" out="" i
  for ((i = 1; i <= n; i++)); do
    [[ -n "$out" ]] && out+=" && "
    out+="$runner s$i"
  done
  printf '%s' "$out"
}

# Run one scenario.
#   $1=name  $2=shell-mode(none|sh)  $3=task/target  $4=graph_n(0)  $5=tools(all|js)
# `js` restricts to the runners that resolve node_modules/.bin (tsr/npm/bun/nub/deno) — the
# only fair set for the local-binary scenario. The list is assembled from what's
# installed.
bench() {
  local name="$1" shellmode="$2" target="$3" graph_n="${4:-0}" tools="${5:-all}"
  local args=(-n tsr "$TSR $target")
  if [[ "$graph_n" -gt 0 ]]; then
    has npm && args+=(-n npm "$(chain 'npm run --silent' "$graph_n")")
    has bun && args+=(-n bun "$(chain 'bun run' "$graph_n")")
    has nub && args+=(-n nub "$(chain 'nub run' "$graph_n")")
    has deno && args+=(-n deno "$(chain 'deno task --quiet' "$graph_n")")
  else
    has npm && args+=(-n npm "npm run --silent $target")
    has bun && args+=(-n bun "bun run $target")
    has nub && args+=(-n nub "nub run $target")
    has deno && args+=(-n deno "deno task --quiet $target")
  fi
  if [[ "$tools" != "js" ]]; then
    has just && args+=(-n just "just $target")
    has task && args+=(-n task "task $target")
    has make && args+=(-n make "make $target")
    has mise && args+=(-n mise "mise run $target")
  fi

  local shellflag=(--shell=none)
  [[ "$shellmode" == "sh" ]] && shellflag=() # default shell for `&&` chains

  echo "== $name ==" >&2
  hyperfine "${shellflag[@]}" \
    --warmup 20 --min-runs 80 \
    --export-json "$out/$name.json" \
    --export-markdown "$out/$name.md" \
    "${args[@]}"
}

# Topological fan-out across a real multi-package workspace (SPEC §5.0). Only the
# runners that actually order packages by dependency take part: tsr (`^build`),
# pnpm (`-r`) and bun (`--filter`). `npm --workspaces` walks packages in *name*
# order, not dependency order — verified against a chain whose correct order is
# the reverse of alphabetical — so it is not doing this job, and is left out
# rather than shown winning a race it is not running. Turbo/Nx are out of scope
# by design: they exist to cache, which tsr delegates rather than reimplements
# (SPEC §11), so a no-op comparison against them would measure nothing real.
bench_topo() {
  # Separate statements on purpose: bash expands every word of a `local` before
  # assigning any of them, so `dir="$here/topo/$n"` on the same line would read an
  # unset `n` (and abort under `set -u`).
  local n="$1"
  local dir="$here/topo/$n"
  [[ -d "$dir" ]] || { echo "skip topo$n — run gen-workspace.sh first" >&2; return; }
  local args=(-n tsr "$TSR build")
  has pnpm && args+=(-n pnpm "pnpm -r --reporter=silent run build")
  has bun && args+=(-n bun "bun run --filter * build")

  echo "== topo$n ==" >&2
  (
    cd "$dir"
    hyperfine --shell=none --warmup 20 --min-runs 80 \
      --export-json "$out/topo$n.json" \
      --export-markdown "$out/topo$n.md" \
      "${args[@]}"
  )
}

bench startup none noop
bench shell none shell
bench builtins none builtins
bench globbing none globbing
bench localbin none cli 0 js
bench steps5 none steps5
bench graph5 sh graph5 5
bench graph10 sh graph10 10

bench_topo 10
bench_topo 50
bench_topo 200

echo "results in benches/results/{startup,shell,builtins,globbing,localbin,steps5,graph5,graph10,topo10,topo50,topo200}.{md,json}" >&2
